[package]
name = "fselect"
version = "0.0.9"
authors = ["jhspetersson <jhspetersson@gmail.com>"]
description = "Find files with SQL-like queries"
keywords = ["find", "files", "sql", "query", "tool"]
categories = ["filesystem", "command-line-utilities", "command-line-interface"]
documentation = "https://github.com/jhspetersson/fselect"
homepage = "https://github.com/jhspetersson/fselect"
repository = "https://github.com/jhspetersson/fselect"
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
chrono = "0.4"
regex = "0.2"
term = "0.4"

[target.'cfg(unix)'.dependencies]
users = "0.6.0"