[package]
name = "fselect"
version = "0.3.1"
authors = ["jhspetersson <jhspetersson@gmail.com>"]
description = "Find files with SQL-like queries"
keywords = ["find", "files", "sql", "query", "tool"]
categories = ["filesystem", "command-line-utilities", "command-line-interface"]
documentation = "https://github.com/jhspetersson/fselect/blob/master/docs/usage.md"
homepage = "https://github.com/jhspetersson/fselect"
repository = "https://github.com/jhspetersson/fselect"
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
chrono = "0.4"
csv = "1.0.0-beta.5"
humansize = "1.1.0"
imagesize = "0.5"
regex = "0.2"
serde_json = "1.0"
term = "0.5"
zip = "0.3.1"

[target.'cfg(unix)'.dependencies]
users = "0.6.0"