[package]
name = "fselect"
version = "0.3.2"
authors = ["jhspetersson <jhspetersson@gmail.com>"]
description = "Find files with SQL-like queries"
keywords = ["find", "files", "sql", "query", "tool"]
categories = ["filesystem", "command-line-utilities", "command-line-interface"]
documentation = "https://github.com/jhspetersson/fselect/blob/master/docs/usage.md"
homepage = "https://github.com/jhspetersson/fselect"
repository = "https://github.com/jhspetersson/fselect"
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
chrono = "0.4"
csv = "1.0"
humansize = "1.1"
imagesize = "0.5"
mp3-metadata = "0.3"
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
term = "0.5"
time = "0.1"
zip = "0.3"

[target.'cfg(unix)'.dependencies]
users = "0.6"
xattr = "0.2"